package defpackage;

import com.ishumei.smantifraud.l1l11lI1l;
import com.tencent.mm.opensdk.modelmsg.WXMediaMessage;
import com.tencent.rtmp.TXLiveConstants;
import com.tencent.trtc.TRTCCloudDef;
import java.util.HashMap;
import org.scilab.forge.jlatexmath.a;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes3.dex */
public final class bd8 {
    static {
        HashMap hashMap = a.f;
        hashMap.put("newcommand", new ad8(0, 2, 2));
        hashMap.put("renewcommand", new ad8(1, 2, 2));
        hashMap.put("rule", new ad8(2, 2, 1));
        hashMap.put("hspace", new ad8(3, 1));
        hashMap.put("vspace", new ad8(4, 1));
        hashMap.put("llap", new ad8(5, 1));
        hashMap.put("rlap", new ad8(6, 1));
        hashMap.put("clap", new ad8(7, 1));
        hashMap.put("mathllap", new ad8(8, 1));
        hashMap.put("mathrlap", new ad8(9, 1));
        hashMap.put("mathclap", new ad8(10, 1));
        hashMap.put("includegraphics", new ad8(11, 1, 1));
        hashMap.put("cfrac", new ad8(12, 2, 1));
        hashMap.put("frac", new ad8(13, 2));
        hashMap.put("sfrac", new ad8(14, 2));
        hashMap.put("genfrac", new ad8(15, 6));
        hashMap.put("over", new ad8(16, 0));
        hashMap.put("overwithdelims", new ad8(17, 2));
        hashMap.put("atop", new ad8(18, 0));
        hashMap.put("atopwithdelims", new ad8(19, 2));
        hashMap.put("choose", new ad8(20, 0));
        hashMap.put("underscore", new ad8(21, 0));
        hashMap.put("mbox", new ad8(22, 1));
        hashMap.put("text", new ad8(23, 1));
        hashMap.put("intertext", new ad8(24, 1));
        hashMap.put("binom", new ad8(25, 2));
        hashMap.put("mathbf", new ad8(26, 1));
        hashMap.put("bf", new ad8(27, 0));
        hashMap.put("mathbb", new ad8(28, 1));
        hashMap.put("mathcal", new ad8(29, 1));
        hashMap.put("cal", new ad8(30, 1));
        hashMap.put("mathit", new ad8(31, 1));
        hashMap.put("it", new ad8(32, 0));
        hashMap.put("mathrm", new ad8(33, 1));
        hashMap.put("rm", new ad8(34, 0));
        hashMap.put("mathscr", new ad8(35, 1));
        hashMap.put("mathsf", new ad8(36, 1));
        hashMap.put("sf", new ad8(37, 0));
        hashMap.put("mathtt", new ad8(38, 1));
        hashMap.put("tt", new ad8(39, 0));
        hashMap.put("mathfrak", new ad8(40, 1));
        hashMap.put("mathds", new ad8(41, 1));
        hashMap.put("frak", new ad8(42, 1));
        hashMap.put("Bbb", new ad8(43, 1));
        hashMap.put("oldstylenums", new ad8(44, 1));
        hashMap.put("bold", new ad8(45, 1));
        hashMap.put("^", new ad8(46, 1));
        hashMap.put("'", new ad8(47, 1));
        hashMap.put("\"", new ad8(48, 1));
        hashMap.put("`", new ad8(49, 1));
        hashMap.put("=", new ad8(50, 1));
        hashMap.put(".", new ad8(51, 1));
        hashMap.put("~", new ad8(52, 1));
        hashMap.put("u", new ad8(53, 1));
        hashMap.put("v", new ad8(54, 1));
        hashMap.put("H", new ad8(55, 1));
        hashMap.put("r", new ad8(56, 1));
        hashMap.put("U", new ad8(57, 1));
        hashMap.put("T", new ad8(58, 1));
        hashMap.put("t", new ad8(59, 1));
        hashMap.put("accent", new ad8(60, 2));
        hashMap.put("grkaccent", new ad8(61, 2));
        hashMap.put("hat", new ad8(62, 1));
        hashMap.put("widehat", new ad8(63, 1));
        hashMap.put("tilde", new ad8(64, 1));
        hashMap.put("acute", new ad8(65, 1));
        hashMap.put("grave", new ad8(66, 1));
        hashMap.put("ddot", new ad8(67, 1));
        hashMap.put("cyrddot", new ad8(68, 1));
        hashMap.put("mathring", new ad8(69, 1));
        hashMap.put("bar", new ad8(70, 1));
        hashMap.put("breve", new ad8(71, 1));
        hashMap.put("check", new ad8(72, 1));
        hashMap.put("vec", new ad8(73, 1));
        hashMap.put("dot", new ad8(74, 1));
        hashMap.put("widetilde", new ad8(75, 1));
        hashMap.put("nbsp", new ad8(76, 0));
        hashMap.put("smallmatrix@@env", new ad8(77, 1));
        hashMap.put("matrix@@env", new ad8(78, 1));
        hashMap.put("overrightarrow", new ad8(79, 1));
        hashMap.put("overleftarrow", new ad8(80, 1));
        hashMap.put("overleftrightarrow", new ad8(81, 1));
        hashMap.put("underrightarrow", new ad8(82, 1));
        hashMap.put("underleftarrow", new ad8(83, 1));
        hashMap.put("underleftrightarrow", new ad8(84, 1));
        hashMap.put("xleftarrow", new ad8(85, 1, 1));
        hashMap.put("xrightarrow", new ad8(86, 1, 1));
        hashMap.put("underbrace", new ad8(87, 1));
        hashMap.put("overbrace", new ad8(88, 1));
        hashMap.put("underbrack", new ad8(89, 1));
        hashMap.put("overbrack", new ad8(90, 1));
        hashMap.put("underparen", new ad8(91, 1));
        hashMap.put("overparen", new ad8(92, 1));
        hashMap.put("sqrt", new ad8(93, 1, 1));
        hashMap.put("sqrtsign", new ad8(94, 1));
        hashMap.put("overline", new ad8(95, 1));
        hashMap.put("underline", new ad8(96, 1));
        hashMap.put("mathop", new ad8(97, 1));
        hashMap.put("mathpunct", new ad8(98, 1));
        hashMap.put("mathord", new ad8(99, 1));
        hashMap.put("mathrel", new ad8(100, 1));
        hashMap.put("mathinner", new ad8(WXMediaMessage.IMediaObject.TYPE_NATIVE_GAME_PAGE, 1));
        hashMap.put("mathbin", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_256_144, 1));
        hashMap.put("mathopen", new ad8(103, 1));
        hashMap.put("mathclose", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_320_180, 1));
        hashMap.put("joinrel", new ad8(105, 0));
        hashMap.put("smash", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_480_270, 1, 1));
        hashMap.put("vdots", new ad8(107, 0));
        hashMap.put("ddots", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_640_360, 0));
        hashMap.put("iddots", new ad8(109, 0));
        hashMap.put("nolimits", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_960_540, 0));
        hashMap.put("limits", new ad8(111, 0));
        hashMap.put("normal", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_1280_720, 0));
        hashMap.put("(", new ad8(113, 0));
        hashMap.put("[", new ad8(TRTCCloudDef.TRTC_VIDEO_RESOLUTION_1920_1080, 0));
        hashMap.put("left", new ad8(115, 1));
        hashMap.put("middle", new ad8(116, 1));
        hashMap.put("cr", new ad8(117, 0));
        hashMap.put("multicolumn", new ad8(118, 3));
        hashMap.put("hdotsfor", new ad8(119, 1, 1));
        hashMap.put("array@@env", new ad8(120, 2));
        hashMap.put("align@@env", new ad8(121, 2));
        hashMap.put("aligned@@env", new ad8(122, 2));
        hashMap.put("flalign@@env", new ad8(123, 2));
        hashMap.put("alignat@@env", new ad8(124, 2));
        hashMap.put("alignedat@@env", new ad8(125, 2));
        hashMap.put("multline@@env", new ad8(126, 2));
        hashMap.put("gather@@env", new ad8(127, 2));
        hashMap.put("gathered@@env", new ad8(128, 2));
        hashMap.put("shoveright", new ad8(129, 1));
        hashMap.put("shoveleft", new ad8(130, 1));
        hashMap.put("\\", new ad8(131, 0));
        hashMap.put("newenvironment", new ad8(132, 3));
        hashMap.put("renewenvironment", new ad8(133, 3));
        hashMap.put("makeatletter", new ad8(134, 0));
        hashMap.put("makeatother", new ad8(135, 0));
        hashMap.put("fbox", new ad8(136, 1));
        hashMap.put("boxed", new ad8(137, 1));
        hashMap.put("stackrel", new ad8(138, 2, 1));
        hashMap.put("stackbin", new ad8(139, 2, 1));
        hashMap.put("accentset", new ad8(140, 2));
        hashMap.put("underaccent", new ad8(141, 2));
        hashMap.put("undertilde", new ad8(142, 1));
        hashMap.put("overset", new ad8(143, 2));
        hashMap.put("Braket", new ad8(144, 1));
        hashMap.put("Set", new ad8(145, 1));
        hashMap.put("underset", new ad8(146, 2));
        hashMap.put("boldsymbol", new ad8(147, 1));
        hashMap.put("LaTeX", new ad8(148, 0));
        hashMap.put("GeoGebra", new ad8(149, 0));
        hashMap.put("big", new ad8(150, 1));
        hashMap.put("Big", new ad8(151, 1));
        hashMap.put("bigg", new ad8(152, 1));
        hashMap.put("Bigg", new ad8(153, 1));
        hashMap.put("bigl", new ad8(154, 1));
        hashMap.put("Bigl", new ad8(155, 1));
        hashMap.put("biggl", new ad8(156, 1));
        hashMap.put("Biggl", new ad8(157, 1));
        hashMap.put("bigr", new ad8(158, 1));
        hashMap.put("Bigr", new ad8(159, 1));
        hashMap.put("biggr", new ad8(160, 1));
        hashMap.put("Biggr", new ad8(161, 1));
        hashMap.put("displaystyle", new ad8(162, 0));
        hashMap.put("textstyle", new ad8(163, 0));
        hashMap.put("scriptstyle", new ad8(164, 0));
        hashMap.put("scriptscriptstyle", new ad8(165, 0));
        hashMap.put("sideset", new ad8(166, 3));
        hashMap.put("prescript", new ad8(167, 3));
        hashMap.put("rotatebox", new ad8(168, 2, 1));
        hashMap.put("reflectbox", new ad8(169, 1));
        hashMap.put("scalebox", new ad8(170, 2, 2));
        hashMap.put("resizebox", new ad8(171, 3));
        hashMap.put("raisebox", new ad8(172, 2, 2));
        hashMap.put("shadowbox", new ad8(173, 1));
        hashMap.put("ovalbox", new ad8(174, 1));
        hashMap.put("doublebox", new ad8(175, 1));
        hashMap.put("phantom", new ad8(176, 1));
        hashMap.put("hphantom", new ad8(177, 1));
        hashMap.put("vphantom", new ad8(178, 1));
        hashMap.put("sp@breve", new ad8(179, 0));
        hashMap.put("sp@hat", new ad8(TXLiveConstants.RENDER_ROTATION_180, 0));
        hashMap.put("definecolor", new ad8(181, 3));
        hashMap.put("textcolor", new ad8(182, 2));
        hashMap.put("fgcolor", new ad8(183, 2));
        hashMap.put("bgcolor", new ad8(184, 2));
        hashMap.put("colorbox", new ad8(185, 2));
        hashMap.put("fcolorbox", new ad8(186, 3));
        hashMap.put("c", new ad8(187, 1));
        hashMap.put("IJ", new ad8(188, 0));
        hashMap.put("ij", new ad8(189, 0));
        hashMap.put("TStroke", new ad8(190, 0));
        hashMap.put("tStroke", new ad8(191, 0));
        hashMap.put("Lcaron", new ad8(192, 0));
        hashMap.put("tcaron", new ad8(193, 0));
        hashMap.put("lcaron", new ad8(194, 0));
        hashMap.put("k", new ad8(195, 1));
        hashMap.put("cong", new ad8(196, 0));
        hashMap.put("doteq", new ad8(197, 0));
        hashMap.put("jlmDynamic", new ad8(198, 1, 1));
        hashMap.put("jlmExternalFont", new ad8(199, 1));
        hashMap.put("jlmText", new ad8(200, 1));
        hashMap.put("jlmTextit", new ad8(201, 1));
        hashMap.put("jlmTextbf", new ad8(202, 1));
        hashMap.put("jlmTextitbf", new ad8(203, 1));
        hashMap.put("DeclareMathSizes", new ad8(204, 4));
        hashMap.put("magnification", new ad8(205, 1));
        hashMap.put("hline", new ad8(206, 0));
        hashMap.put("tiny", new ad8(207, 0));
        hashMap.put("scriptsize", new ad8(208, 0));
        hashMap.put("footnotesize", new ad8(209, 0));
        hashMap.put("small", new ad8(210, 0));
        hashMap.put("normalsize", new ad8(211, 0));
        hashMap.put("large", new ad8(212, 0));
        hashMap.put("Large", new ad8(213, 0));
        hashMap.put("LARGE", new ad8(214, 0));
        hashMap.put("huge", new ad8(215, 0));
        hashMap.put("Huge", new ad8(216, 0));
        hashMap.put("jlatexmathcumsup", new ad8(217, 1));
        hashMap.put("jlatexmathcumsub", new ad8(218, 1));
        hashMap.put("hstrok", new ad8(219, 0));
        hashMap.put("Hstrok", new ad8(220, 0));
        hashMap.put("dstrok", new ad8(221, 0));
        hashMap.put("Dstrok", new ad8(222, 0));
        hashMap.put("dotminus", new ad8(223, 0));
        hashMap.put("ratio", new ad8(224, 0));
        hashMap.put("smallfrowneq", new ad8(225, 0));
        hashMap.put("geoprop", new ad8(226, 0));
        hashMap.put("minuscolon", new ad8(227, 0));
        hashMap.put("minuscoloncolon", new ad8(228, 0));
        hashMap.put("simcolon", new ad8(229, 0));
        hashMap.put("simcoloncolon", new ad8(230, 0));
        hashMap.put("approxcolon", new ad8(231, 0));
        hashMap.put("approxcoloncolon", new ad8(232, 0));
        hashMap.put("coloncolon", new ad8(233, 0));
        hashMap.put("equalscolon", new ad8(234, 0));
        hashMap.put("equalscoloncolon", new ad8(235, 0));
        hashMap.put("colonminus", new ad8(236, 0));
        hashMap.put("coloncolonminus", new ad8(237, 0));
        hashMap.put("colonequals", new ad8(238, 0));
        hashMap.put("coloncolonequals", new ad8(239, 0));
        hashMap.put("colonsim", new ad8(240, 0));
        hashMap.put("coloncolonsim", new ad8(241, 0));
        hashMap.put("colonapprox", new ad8(242, 0));
        hashMap.put("coloncolonapprox", new ad8(243, 0));
        hashMap.put("kern", new ad8(244, 1));
        hashMap.put("char", new ad8(245, 1));
        hashMap.put("roman", new ad8(246, 1));
        hashMap.put("Roman", new ad8(247, 1));
        hashMap.put("textcircled", new ad8(248, 1));
        hashMap.put("textsc", new ad8(249, 1));
        hashMap.put("sc", new ad8(250, 0));
        hashMap.put(",", new ad8(251, 0));
        hashMap.put(":", new ad8(252, 0));
        hashMap.put(";", new ad8(253, 0));
        hashMap.put("thinspace", new ad8(254, 0));
        hashMap.put("medspace", new ad8(255, 0));
        hashMap.put("thickspace", new ad8(l1l11lI1l.l111l11111lIl, 0));
        hashMap.put("!", new ad8(257, 0));
        hashMap.put("negthinspace", new ad8(258, 0));
        hashMap.put("negmedspace", new ad8(259, 0));
        hashMap.put("negthickspace", new ad8(260, 0));
        hashMap.put("quad", new ad8(261, 0));
        hashMap.put("surd", new ad8(262, 0));
        hashMap.put("iint", new ad8(263, 0));
        hashMap.put("iiint", new ad8(264, 0));
        hashMap.put("iiiint", new ad8(265, 0));
        hashMap.put("idotsint", new ad8(266, 0));
        hashMap.put("int", new ad8(267, 0));
        hashMap.put("oint", new ad8(268, 0));
        hashMap.put("lmoustache", new ad8(269, 0));
        hashMap.put("rmoustache", new ad8(270, 0));
        hashMap.put("-", new ad8(271, 0));
        hashMap.put("jlmXML", new ad8(272, 1));
        hashMap.put("above", new ad8(273, 0));
        hashMap.put("abovewithdelims", new ad8(274, 2));
        hashMap.put("st", new ad8(275, 1));
        hashMap.put("fcscore", new ad8(276, 1));
        hashMap.put("mathnormal", new ad8(277, 1));
        hashMap.put("qquad", new ad8(278, 0));
        hashMap.put("longdiv", new ad8(279, 2));
        hashMap.put("questeq", new ad8(280, 0));
        hashMap.put("bangle", new ad8(281, 0));
        hashMap.put("brace", new ad8(282, 0));
        hashMap.put("brack", new ad8(283, 0));
        hashMap.put("color", new ad8(182, 2));
    }
}
