package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class cm5 {
    public static final z86 a = new z86("inform7", a64.a, Collections.singletonList("i7"), true, null, false, null, Arrays.asList(new i77(null, null, Collections.singletonList(new i77(null, null, null, null, null, "\\[", null, "\\]", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "subst", null, -161, 383)), null, null, "\"", null, "\"", null, null, null, null, Double.valueOf(0.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -4261, 383), new i77(null, null, null, null, null, "^(Volume|Book|Part|Chapter|Section|Table)\\b", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "section", null, -161, 383), new i77(null, null, Collections.singletonList(new i77(null, null, null, null, null, "\\(This", null, "\\)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -161, 511)), null, null, "^(Check|Carry out|Report|Instead of|To|Rule|When|Before|After)\\b", null, ":", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -165, 511), new i77(null, null, Collections.singletonList(new k77()), null, null, "\\[", null, "\\]", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", null, -165, 383)), null, Collections.singletonMap("keyword", "thing room person man woman animal container supporter backdrop door scenery open closed locked inside gender is are say understand kind of rule"), null, 27504);
}
