package defpackage;

import com.ishumei.smantifraud.l111l1111llIl;
import com.ishumei.smantifraud.l11l11I1111l;
import com.ishumei.smantifraud.l1l1l11Il;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class irb {
    public static final z86 a;

    static {
        List singletonList = Collections.singletonList("zig");
        Map I0 = os6.I0(new pz7("keyword", Arrays.asList("inline", "while", "for", "extern", "packed", "export", "pub", "noalias", "comptime", "volatile", "align", "linksection", "threadlocal", "allowzero", "noinline", "callconv", "struct", "enum", "const", "union", "opaque", "asm", "unreachable", "break", "return", "continue", "defer", "errdefer", "await", "resume", "suspend", "async", "nosuspend", "try", "catch", "if", "else", "switch", "orelse", "usingnamespace", "test", "and", "or", "bool", "void", l11l11I1111l.l111l1111l1Il, "blk", "var")), new pz7("literal", Arrays.asList("true", "false", "null", "undefined")), new pz7("built_in", Arrays.asList("std", "meme", "@This", "@Import", "@ass", "i8", "i16", "i32", "i64", "i128", "u8", "u16", "u32", "u64", "u128", "f16", "f32", "f64", "usize", "isize", "c_short", "c_int", "c_long", "c_longlong", "c_ushort", "c_uint", "c_ulong", "c_ulonglong", "c_float", "c_double", "c_void", l1l1l11Il.l11l111lll)), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("anytype", "noreturn", "error", "anyerror", "anyframe", "anyopaque")), new pz7(l111l1111llIl.l11l1111I11l, Arrays.asList("+", "-", "*", "/", "%", "==", "!=", "<", ">", "<=", ">=")));
        i77 i77Var = new i77(null, null, null, null, null, "\\bmem\\.Copy\\b", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "built_in", null, -33, 383);
        i77 i77Var2 = new i77(null, null, null, null, null, "\\|[a-zA-Z_]+\\|", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta-event", null, -33, 383);
        i77 i77Var3 = new i77(null, null, null, null, null, "\\/\\/\\s*TODO:.*$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment-todo", null, -33, 383);
        i77 i77Var4 = new i77(null, null, null, null, null, "\\/\\/[^\\n]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", null, -33, 383);
        i77 i77Var5 = new i77(null, null, null, null, null, "!(?=\\w+)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "errorhandling", null, -33, 383);
        i77 i77Var6 = new i77(null, null, null, null, null, "\\?(?=[a-zA-Z_])", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "optional", null, -33, 383);
        i77 i77Var7 = new i77(null, null, null, null, null, "[-+%/*=<>!]=?|&&|\\|\\||<<=?|>>=?|\\*\\*|\\+\\+|--|\\->", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, l111l1111llIl.l11l1111I11l, null, -33, 383);
        i77 i77Var8 = new i77(null, null, null, null, null, "\\.\\w+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "property", null, -33, 383);
        i77 i77Var9 = vy2.e;
        i77 i77Var10 = new i77(null, null, null, null, null, "@[a-zA-Z_]\\w*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -33, 383);
        i77 i77Var11 = new i77(null, null, null, null, null, "@[a-zA-Z_]\\w*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -33, 383);
        i77 i77Var12 = new i77(null, null, null, null, null, "'[a-zA-Z_][a-zA-Z0-9_]*'", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "symbol", null, -33, 383);
        i77 i77Var13 = new i77(null, null, null, null, null, "\\\\[xuU][a-fA-F0-9]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "literal", null, -33, 383);
        i77 i77Var14 = new i77(null, null, null, null, null, "\\b0x[0-9a-fA-F]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -33, 383);
        i77 i77Var15 = new i77(null, null, null, null, null, "\\b0b[01]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -33, 383);
        i77 i77Var16 = new i77(null, null, null, null, null, "\\b0o[0-7]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -33, 383);
        i77 i77Var17 = new i77(null, null, null, null, null, "\\b[0-9]+\\b", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -33, 383);
        i77 i77Var18 = new i77(null, null, null, null, null, "[a-zA-Z_][a-zA-Z0-9_]*", null, null, null, null, null, null, Double.valueOf(0.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title", -4129, 255);
        i77 i77Var19 = vy2.f;
        List asList = Arrays.asList(i77Var9, i77Var19);
        Boolean bool = Boolean.TRUE;
        a = new z86("zig", a64.a, singletonList, false, null, false, null, Arrays.asList(i77Var, i77Var2, i77Var3, i77Var4, i77Var5, i77Var6, i77Var7, i77Var8, i77Var9, vy2.c, vy2.b, vy2.i, i77Var10, i77Var11, i77Var12, i77Var13, i77Var14, i77Var15, i77Var16, i77Var17, vy2.k, new i77(null, null, Arrays.asList(i77Var18, new i77(null, null, asList, null, null, "\\(", null, "\\)", null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -1189, 383)), null, null, null, "fn", "\\{", null, null, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "function", null, -131269, 383), new i77(null, null, Collections.singletonList(new i77(null, null, Arrays.asList(i77Var9, i77Var19), null, null, "\\(", null, "\\)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -165, 383)), null, null, "[a-zA-Z_][a-zA-Z0-9_]*\\(", null, "\\)", null, null, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "function-call", null, -131237, 383), new i77(null, null, null, null, null, "@[a-zA-Z_][a-zA-Z0-9_]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "macro", null, -33, 383)), "\\/\\*", I0, null, 25464);
    }
}
