package defpackage;

import com.ishumei.sdk.captcha.SmCaptchaWebView;
import com.ishumei.smantifraud.l11l11I1111l;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class j05 {
    public static final z86 a;

    static {
        List singletonList = Collections.singletonList("golang");
        Map I0 = os6.I0(new pz7("keyword", Arrays.asList("break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough", "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range", "return", SmCaptchaWebView.MODE_SELECT, "struct", "switch", l11l11I1111l.l111l1111l1Il, "var")), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("bool", "byte", "complex64", "complex128", "error", "float32", "float64", "int8", "int16", "int32", "int64", "string", "uint8", "uint16", "uint32", "uint64", "int", "uint", "uintptr", "rune")), new pz7("literal", Arrays.asList("true", "false", "iota", "nil")), new pz7("built_in", Arrays.asList("append", "cap", "close", "complex", "copy", "imag", "len", "make", "new", "panic", "print", "println", "real", "recover", "delete")));
        i77 i77Var = new i77(null, null, null, Arrays.asList(vy2.c, vy2.b, new i77(null, null, null, null, null, "`", null, "`", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -161, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -9, 383);
        Double valueOf = Double.valueOf(0.0d);
        i77 i77Var2 = new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "-?\\b0[xX]\\.[a-fA-F0-9](_?[a-fA-F0-9])*[pP][+-]?\\d(_?\\d)*i?", null, null, null, null, null, null, null, null, null, null, null, -536875009, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "-?\\b0[xX](_?[a-fA-F0-9])+((\\.([a-fA-F0-9](_?[a-fA-F0-9])*)?)?[pP][+-]?\\d(_?\\d)*)?i?", null, null, null, null, null, null, null, null, null, null, null, -536875009, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "-?\\b0[oO](_?[0-7])*i?", null, null, null, null, null, null, null, null, null, null, null, -536875009, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "-?\\.\\d(_?\\d)*([eE][+-]?\\d(_?\\d)*)?i?", null, null, null, null, null, null, null, null, null, null, null, -536875009, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "-?\\b\\d(_?\\d)*(\\.(\\d(_?\\d)*)?)?([eE][+-]?\\d(_?\\d)*)?i?", null, null, null, null, null, null, null, null, null, null, null, -536875009, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -9, 383);
        i77 i77Var3 = new i77(null, null, null, null, null, ":=", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511);
        Map I02 = os6.I0(new pz7("keyword", Arrays.asList("break", "case", "chan", "const", "continue", "default", "defer", "else", "fallthrough", "for", "func", "go", "goto", "if", "import", "interface", "map", "package", "range", "return", SmCaptchaWebView.MODE_SELECT, "struct", "switch", l11l11I1111l.l111l1111l1Il, "var")), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("bool", "byte", "complex64", "complex128", "error", "float32", "float64", "int8", "int16", "int32", "int64", "string", "uint8", "uint16", "uint32", "uint64", "int", "uint", "uintptr", "rune")), new pz7("literal", Arrays.asList("true", "false", "iota", "nil")), new pz7("built_in", Arrays.asList("append", "cap", "close", "complex", "copy", "imag", "len", "make", "new", "panic", "print", "println", "real", "recover", "delete")));
        Boolean bool = Boolean.TRUE;
        a = new z86("go", a64.a, singletonList, false, null, false, null, Arrays.asList(vy2.e, vy2.f, i77Var, i77Var2, i77Var3, new i77(null, null, Arrays.asList(vy2.l, new i77(I02, "[\"']", null, null, null, "\\(", null, "\\)", null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -1188, 383)), null, null, null, "func", "\\s*(\\{|$)", null, null, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "function", null, -131269, 383)), "</", I0, null, 25464);
    }
}
