package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class ku3 {
    public static final z86 a = new z86("diff", a64.a, Collections.singletonList("patch"), false, null, false, null, Arrays.asList(new i77(null, null, null, null, null, null, null, null, null, null, null, null, Double.valueOf(10.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "(?:^@@ +-\\d+,\\d+ +\\+\\d+,\\d+ +@@|^\\*\\*\\* +\\d+,\\d+ +\\*\\*\\*\\*$|^--- +\\d+,\\d+ +----$)", null, null, null, null, null, null, null, null, null, "meta", null, -536875009, 383), new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, "(?:Index: |^index|={3,}|^-{3}|^\\*{3} |^\\+{3}|^diff --git)", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -161, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "^\\*{15}$", null, null, null, null, null, null, null, null, null, null, null, -536870913, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", null, -9, 383), new i77(null, null, null, null, null, "^\\+", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "addition", null, -161, 383), new i77(null, null, null, null, null, "^-", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "deletion", null, -161, 383), new i77(null, null, null, null, null, "^!", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "addition", null, -161, 383)), null, null, null, 31608);
}
