package defpackage;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class mc3 {
    public static final z86 a;

    static {
        List asList = Arrays.asList("crm", "pcmk");
        Map I0 = os6.I0(new pz7("keyword", "params meta operations op rule attributes utilization read write deny defined not_defined in_range date spec in ref reference attribute type xpath version and or lt gt tag lte gte eq ne \\ number string"), new pz7("literal", "Master Started Slave Stopped start promote demote stop monitor true false"));
        i77 i77Var = new i77(null, null, null, null, new i77(null, null, null, null, new i77(null, null, null, null, null, null, null, "\\s*[\\$\\w_][\\w_-]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title", null, -129, 383), null, null, "\\s*([\\w_-]+:)?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -145, 511), null, "node", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -81, 511);
        i77 i77Var2 = new i77(null, null, null, null, new i77(null, null, null, null, new i77(null, null, null, null, null, null, null, "\\s*@?[\\w_][\\w_\\.:-]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -129, 511), null, null, "\\s*[\\$\\w_][\\w_-]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title", null, -145, 383), null, "primitive rsc_template", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -81, 511);
        i77 i77Var3 = new i77("group clone ms master location colocation order fencing_topology rsc_ticket acl_target acl_group user role tag xml", null, null, null, new i77(null, null, null, null, null, null, null, "[\\$\\w_][\\w_-]*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title", null, -129, 383), "\\b(group|clone|ms|master|location|colocation|order|fencing_topology|rsc_ticket|acl_target|acl_group|user|role|tag|xml)\\s+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -50, 511);
        i77 i77Var4 = new i77(null, null, null, null, new i77(null, null, null, null, null, null, null, "\\s*([\\w_-]+:)?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title", null, -129, 383), null, "property rsc_defaults op_defaults", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -81, 511);
        Double valueOf = Double.valueOf(0.0d);
        a = new z86("crmsh", a64.a, asList, true, null, false, null, Arrays.asList(vy2.g, i77Var, i77Var2, i77Var3, i77Var4, vy2.c, new i77(null, null, null, null, null, "(ocf|systemd|service|lsb):[\\w_:-]+", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -4129, 383), new i77(null, null, null, null, null, "\\b\\d+(\\.\\d+)?(ms|s|h|m)?", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -4129, 383), new i77(null, null, null, null, null, "[-]?(infinity|inf)", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "literal", null, -4129, 383), new i77(null, null, null, null, null, "([A-Za-z$_#][\\w_-]+)=", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "attr", null, -4129, 383), new i77(null, null, null, null, null, "</?", null, "/?>", null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "tag", null, -4257, 383)), null, I0, null, 27504);
    }
}
