package defpackage;

import com.ishumei.smantifraud.l11l11I1111l;
import java.util.Arrays;
import java.util.Collections;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class mk7 {
    public static final z86 a;

    static {
        Map I0 = os6.I0(new pz7("keyword", Arrays.asList("addr", "and", "as", "asm", "bind", "block", "break", "case", "cast", "const", "continue", "converter", "discard", "distinct", "div", "do", "elif", "else", "end", "enum", "except", "export", "finally", "for", "from", "func", "generic", "guarded", "if", "import", "in", "include", "interface", "is", "isnot", "iterator", "let", "macro", "method", "mixin", "mod", "nil", "not", "notin", "object", "of", "or", "out", "proc", "ptr", "raise", "ref", "return", "shared", "shl", "shr", "static", "template", "try", "tuple", l11l11I1111l.l111l1111l1Il, "using", "var", "when", "while", "with", "without", "xor", "yield")), new pz7("literal", Arrays.asList("true", "false")), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "float", "float32", "float64", "bool", "char", "string", "cstring", "pointer", "expr", "stmt", "void", "auto", "any", "range", "array", "openarray", "varargs", "seq", "set", "clong", "culong", "cchar", "cschar", "cshort", "cint", "csize", "clonglong", "cfloat", "cdouble", "clongdouble", "cuchar", "cushort", "cuint", "culonglong", "cstringarray", "semistatic")), new pz7("built_in", Arrays.asList("stdin", "stdout", "stderr", "result")));
        i77 i77Var = new i77(null, null, null, null, null, "\\{\\.", null, "\\.\\}", null, null, null, null, Double.valueOf(10.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -4257, 383);
        i77 i77Var2 = new i77(null, null, Collections.singletonList(new i77(null, null, null, null, null, "\"\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, "[a-zA-Z]\\w*\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -165, 383);
        i77 i77Var3 = new i77(null, null, null, null, null, "([a-zA-Z]\\w*)?\"\"\"", null, "\"\"\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -161, 383);
        Double valueOf = Double.valueOf(0.0d);
        a = new z86("nim", a64.a, null, false, null, false, null, Arrays.asList(i77Var, i77Var2, i77Var3, vy2.c, new i77(null, null, null, null, null, "\\b[A-Z]\\w+\\b", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, l11l11I1111l.l111l1111l1Il, null, -4129, 383), new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, "\\b(0[xX][0-9a-fA-F][_0-9a-fA-F]*)('?[iIuU](8|16|32|64))?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "\\b(0o[0-7][_0-7]*)('?[iIuUfF](8|16|32|64))?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "\\b(0(b|B)[01][_01]*)('?[iIuUfF](8|16|32|64))?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "\\b(\\d[_\\d]*)('?[iIuUfF](8|16|32|64))?", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -4105, 383), vy2.g), null, I0, null, 27516);
    }
}
