package defpackage;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class mx2 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = rz7.o;
        a = j2;
        b = rz7.c;
        c = rz7.d;
        d = rz7.m;
        long j3 = rz7.x;
        e = j3;
        f = rz7.h;
        long j4 = rz7.f;
        g = j4;
        h = rz7.b;
        i = rz7.a;
        j = rz7.u;
        long j5 = rz7.t;
        k = j5;
        l = j5;
        m = rz7.v;
        n = rz7.A;
        long j6 = rz7.z;
        o = j6;
        p = j6;
        q = rz7.B;
        r = j4;
        s = rz7.p;
        t = rz7.G;
        long j7 = rz7.F;
        u = j7;
        v = j7;
        w = rz7.H;
        x = rz7.q;
        y = rz7.r;
        z = rz7.w;
        long j8 = rz7.y;
        A = j8;
        B = j8;
        C = j3;
        D = rz7.e;
        E = rz7.C;
        long j9 = rz7.E;
        F = j9;
        G = j9;
        H = rz7.D;
        I = j2;
        J = j2;
        K = rz7.l;
        L = rz7.k;
        M = rz7.j;
        N = rz7.n;
        O = rz7.g;
        P = rz7.i;
        Q = rz7.s;
        R = rz7.I;
        long j10 = rz7.K;
        S = j10;
        T = j10;
        U = rz7.J;
    }
}
