package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class ofa {
    public static final z86 a = new z86("tap", a64.a, null, true, null, false, null, Arrays.asList(vy2.g, new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, "^TAP version (\\d+)$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "^1\\.\\.(\\d+)$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -9, 383), new i77(null, null, null, null, null, "---$", null, "\\.\\.\\.$", null, null, null, null, Double.valueOf(0.0d), null, Collections.singletonList("yaml"), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -37025, 511), new i77(null, null, null, null, null, " (\\d+) ", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -33, 383), new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, "^ok", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "^not ok", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "symbol", null, -9, 383)), null, null, null, 31604);
}
