package defpackage;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public final class qx2 {
    public final long A;
    public final long B;
    public final long C;
    public final long D;
    public final long E;
    public final long F;
    public final long G;
    public final long H;
    public final long I;
    public final long J;
    public final long K;
    public final long L;
    public final long M;
    public final long N;
    public final long O;
    public final long P;
    public final long Q;
    public final long R;
    public final long S;
    public final long T;
    public final long U;
    public final long V;
    public is0 W;
    public is0 X;
    public vpa Y;
    public ne5 Z;
    public final long a;
    public in8 a0;
    public final long b;
    public wv9 b0;
    public final long c;
    public xba c0;
    public final long d;
    public final long e;
    public final long f;
    public final long g;
    public final long h;
    public final long i;
    public final long j;
    public final long k;
    public final long l;
    public final long m;
    public final long n;
    public final long o;
    public final long p;
    public final long q;
    public final long r;
    public final long s;
    public final long t;
    public final long u;
    public final long v;
    public final long w;
    public final long x;
    public final long y;
    public final long z;

    public qx2(long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42, long j43, long j44, long j45, long j46, long j47, long j48) {
        this.a = j;
        this.b = j2;
        this.c = j3;
        this.d = j4;
        this.e = j5;
        this.f = j6;
        this.g = j7;
        this.h = j8;
        this.i = j9;
        this.j = j10;
        this.k = j11;
        this.l = j12;
        this.m = j13;
        this.n = j14;
        this.o = j15;
        this.p = j16;
        this.q = j17;
        this.r = j18;
        this.s = j19;
        this.t = j20;
        this.u = j21;
        this.v = j22;
        this.w = j23;
        this.x = j24;
        this.y = j25;
        this.z = j26;
        this.A = j27;
        this.B = j28;
        this.C = j29;
        this.D = j30;
        this.E = j31;
        this.F = j32;
        this.G = j33;
        this.H = j34;
        this.I = j35;
        this.J = j36;
        this.K = j37;
        this.L = j38;
        this.M = j39;
        this.N = j40;
        this.O = j41;
        this.P = j42;
        this.Q = j43;
        this.R = j44;
        this.S = j45;
        this.T = j46;
        this.U = j47;
        this.V = j48;
    }

    public final String toString() {
        StringBuilder sb = new StringBuilder("ColorScheme(primary=");
        ln5.t(this.a, "onPrimary=", sb);
        ln5.t(this.b, "primaryContainer=", sb);
        ln5.t(this.c, "onPrimaryContainer=", sb);
        long j = this.d;
        ln5.t(j, "inversePrimary=", sb);
        ln5.t(this.e, "secondary=", sb);
        ln5.t(this.f, "onSecondary=", sb);
        ln5.t(this.g, "secondaryContainer=", sb);
        ln5.t(this.h, "onSecondaryContainer=", sb);
        ln5.t(this.i, "tertiary=", sb);
        ln5.t(this.j, "onTertiary=", sb);
        ln5.t(this.k, "tertiaryContainer=", sb);
        ln5.t(this.l, "onTertiaryContainer=", sb);
        ln5.t(this.m, "background=", sb);
        ln5.t(this.n, "onBackground=", sb);
        ln5.t(this.o, "surface=", sb);
        ln5.t(this.p, "onSurface=", sb);
        ln5.t(this.q, "surfaceVariant=", sb);
        ln5.t(this.r, "onSurfaceVariant=", sb);
        ln5.t(this.s, "surfaceTint=", sb);
        ln5.t(this.t, "inverseSurface=", sb);
        ln5.t(this.u, "inverseOnSurface=", sb);
        ln5.t(this.v, "error=", sb);
        ln5.t(this.w, "onError=", sb);
        ln5.t(this.x, "errorContainer=", sb);
        ln5.t(this.y, "onErrorContainer=", sb);
        ln5.t(this.z, "outline=", sb);
        ln5.t(this.A, "outlineVariant=", sb);
        ln5.t(this.B, "scrim=", sb);
        ln5.t(this.C, "surfaceBright=", sb);
        ln5.t(this.D, "surfaceDim=", sb);
        ln5.t(this.E, "surfaceContainer=", sb);
        ln5.t(this.F, "surfaceContainerHigh=", sb);
        ln5.t(this.G, "surfaceContainerHighest=", sb);
        ln5.t(this.H, "surfaceContainerLow=", sb);
        ln5.t(this.I, "surfaceContainerLowest=", sb);
        ln5.t(this.J, "primaryFixed=", sb);
        ln5.t(this.K, "primaryFixedDim=", sb);
        ln5.t(this.L, "onPrimaryFixed=", sb);
        ln5.t(j, "onPrimaryFixedVariant=", sb);
        ln5.t(this.N, "secondaryFixed=", sb);
        ln5.t(this.O, "secondaryFixedDim=", sb);
        ln5.t(this.P, "onSecondaryFixed=", sb);
        ln5.t(this.Q, "onSecondaryFixedVariant=", sb);
        ln5.t(this.R, "tertiaryFixed=", sb);
        ln5.t(this.S, "tertiaryFixedDim=", sb);
        ln5.t(this.T, "onTertiaryFixed=", sb);
        ln5.t(this.U, "onTertiaryFixedVariant=", sb);
        sb.append((Object) gx2.i(this.V));
        sb.append(')');
        return sb.toString();
    }
}
