package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class rz4 {
    public static final z86 a = new z86("gherkin", a64.a, Collections.singletonList("feature"), false, null, false, null, Arrays.asList(new i77(null, null, null, null, null, "\\*", null, null, null, null, null, null, Double.valueOf(0.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "symbol", null, -4129, 383), new i77(null, null, null, null, null, "@[^@\\s]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -33, 383), new i77(null, null, Collections.singletonList(new i77(null, null, null, null, null, "[^|]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -33, 383)), null, null, "\\|", null, "\\|\\w*$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -165, 511), new i77(null, null, null, null, null, "<", null, ">", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "variable", null, -161, 383), vy2.g, new i77(null, null, null, null, null, "\"\"\"", null, "\"\"\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -161, 383), vy2.c), null, "Feature Background Ability Business Need Scenario Scenarios Scenario Outline Scenario Template Examples Given And Then But When", null, 27512);
}
