package defpackage;

import cn.fly.verify.BuildConfig;
import com.ishumei.smantifraud.l111l1111llIl;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class t04 {
    public static final z86 a;

    static {
        List asList = Arrays.asList(new i77(null, null, null, null, null, "\\b(\\d+(\\.\\d*)?|\\.\\d+)(u|U|l|L|ul|UL|f|F)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "(-?)(\\b0[xX][a-fA-F0-9]+|(\\b\\d+(\\.\\d*)?|\\.\\d+)([eE][-+]?\\d+)?)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511));
        Double valueOf = Double.valueOf(0.0d);
        pz7 pz7Var = new pz7("~contains~7~contains~0", new i77(null, null, null, asList, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -4105, 383));
        pz7 pz7Var2 = new pz7("~contains~11~variants~2", new i77(null, ".", null, null, null, "'\\\\?.", null, "'", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -163, 511));
        i77 i77Var = vy2.a;
        Map I0 = os6.I0(pz7Var, pz7Var2, new pz7("~contains~11~variants~1", new i77(null, null, Collections.singletonList(i77Var), null, null, "(u8?|U)?R\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -165, 511)), new pz7("~contains~11~variants~0", new i77(null, "\\n", Collections.singletonList(i77Var), null, null, "((u8?|U)|L)?\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", -167, 255)), new pz7("~contains~11", new i77(null, null, null, Arrays.asList(new j77("~contains~11~variants~0"), new j77("~contains~11~variants~1"), new j77("~contains~11~variants~2")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -9, 383)), new pz7("~contains~1", new i77(null, null, null, null, null, "&[a-z\\d_]*\\b", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "variable", null, -33, 383)));
        i77 i77Var2 = new i77(null, null, null, null, null, "^\\/(?=\\s*\\{)", null, null, null, null, null, null, Double.valueOf(10.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title.class", null, -4129, 383);
        j77 j77Var = new j77("~contains~1");
        i77 i77Var3 = new i77(null, null, null, null, null, "/[a-z][a-z\\d-]*/", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "keyword", null, -33, 383);
        i77 i77Var4 = new i77(null, null, null, null, null, "^\\s*[a-zA-Z_][a-zA-Z\\d_]*:", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "symbol", null, -33, 383);
        i77 i77Var5 = new i77(null, null, null, null, null, "[a-zA-Z_][a-zA-Z\\d_@-]*(?=\\s\\{)", null, null, null, null, null, null, Double.valueOf(0.2d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "title.class", null, -4129, 383);
        i77 i77Var6 = new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Arrays.asList("[a-z][a-z-,]+", "\\s*", "="), null, null, null, null, null, null, null, null, null, null, os6.I0(new pz7("1", "attr"), new pz7("3", l111l1111llIl.l11l1111I11l)), -536875009, 255);
        i77 i77Var7 = new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "[a-z][a-z-,]+(?=;)", null, null, null, null, null, null, null, null, null, null, "attr", -536875009, 255);
        i77 i77Var8 = new i77(null, null, Arrays.asList(new j77("~contains~7~contains~0"), new j77("~contains~1")), null, null, "<", null, ">", null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -4261, 383);
        i77 i77Var9 = vy2.e;
        i77 i77Var10 = vy2.f;
        a = new z86("dts", I0, null, false, null, false, null, Arrays.asList(i77Var2, j77Var, i77Var3, i77Var4, i77Var5, i77Var6, i77Var7, i77Var8, i77Var9, i77Var10, new j77("~contains~7~contains~0"), new j77("~contains~11"), new i77(Collections.singletonMap("keyword", "if else elif endif define undef ifdef ifndef"), null, Arrays.asList(new i77(null, null, null, null, null, "\\\\\\n", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511), new i77(Collections.singletonMap("keyword", "include"), null, Arrays.asList(new i77(null, null, null, Arrays.asList(new j77("~contains~11~variants~0"), new j77("~contains~11~variants~1"), new j77("~contains~11~variants~2")), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -9, 383), new i77(null, "\\n", null, null, null, "<", null, ">", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -163, 383)), null, null, null, "include", "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -198, 511), new j77("~contains~11"), i77Var9, i77Var10), null, null, "#", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -166, 383), new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "\\};|[;{}]", null, null, null, null, null, null, null, null, null, null, "punctuation", -536875009, 255), new i77(BuildConfig.FLAVOR, null, null, null, null, "[a-zA-Z]\\w*::", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -34, 511)), null, null, null, 31612);
    }
}
