package defpackage;

import cn.fly.verify.BuildConfig;
import com.ishumei.smantifraud.l11l11IIII1l;
import java.util.HashSet;
import java.util.Set;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class wt2 {
    public static final boolean A;
    public static final boolean B;
    public static final boolean C;
    public static final boolean D;
    public static final boolean E;
    public static final boolean F;
    public static final boolean G;
    public static final String H;
    public static final String I;
    public static final String J;
    public static final String K;
    public static final String L;
    public static final String M;
    public static final int N;
    public static final uc9 O;
    public static final String P;
    public static final boolean Q;
    public static final boolean R;
    public static final boolean S;
    public static final String T;
    public static final boolean U;
    public static final int V;
    public static final int W;
    public static final int X;
    public static final boolean Y;
    public static final boolean Z;
    public static final boolean a0;
    public static final boolean b0;
    public static final HashSet d;
    public static final Set e;
    public static final boolean f;
    public static final String g;
    public static final int h;
    public static final int i;
    public static final int j;
    public static final int k;
    public static final int l;
    public static final int m;
    public static final int n;
    public static final int o;
    public static final int p;
    public static final int q;
    public static final int r;
    public static final int s;
    public static final int t;
    public static final int u;
    public static final int v;
    public static final int w;
    public static final int x;
    public static final int y;
    public static final boolean z;
    public static final HashSet a = gl3.a;
    public static final String b = "https://download.deepseek.com/app?utm_source=android_app";
    public static final boolean c = true;

    static {
        HashSet hashSet = new HashSet(ps6.F0(6));
        x00.q0(new String[]{"/api/v0/users/register", "/api/v0/users/register_by_mobile", "/api/v0/users/login_by_mobile_sms", "/api/v0/users/oauth/google/login", "/api/v0/users/create_sms_verification_code", "/api/v0/users/create_email_verification_code"}, hashSet);
        d = hashSet;
        e = x00.x0(new String[]{"search", "deep_think", "completion", "file"});
        f = true;
        g = BuildConfig.FLAVOR;
        h = 21600;
        i = l11l11IIII1l.l111l11111I1l;
        j = l11l11IIII1l.l111l11111I1l;
        k = l11l11IIII1l.l111l11111I1l;
        l = l11l11IIII1l.l111l11111I1l;
        m = l11l11IIII1l.l111l11111I1l;
        n = 3000;
        o = 5000;
        p = 240;
        q = 240;
        r = -1;
        s = -1;
        t = 1000;
        u = 1000;
        v = 5000;
        w = 1000;
        x = 1;
        y = 1;
        z = true;
        A = true;
        B = true;
        C = true;
        D = true;
        E = true;
        F = true;
        G = true;
        H = "https://static.deepseek.com/faq/index.html";
        I = "keep";
        J = "keep";
        K = "keep";
        L = "indeterminate";
        M = "keep";
        N = 600;
        O = new uc9();
        P = "files.deepseeksvc.com";
        Q = true;
        R = true;
        S = true;
        T = BuildConfig.FLAVOR;
        U = true;
        V = 50;
        W = 99;
        X = 2500;
        Y = true;
        Z = true;
        a0 = true;
        b0 = true;
    }
}
