package defpackage;

import com.ishumei.smantifraud.l11l11I1111l;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class yo7 {
    public static final z86 a;

    static {
        List asList = Arrays.asList("mm", "objc", "obj-c", "obj-c++", "objective-c", "objective-c++");
        Map I0 = os6.I0(new pz7("variable.language", Arrays.asList("this", "super")), new pz7("$pattern", "[a-zA-Z@][a-zA-Z0-9_]*"), new pz7("keyword", Arrays.asList("while", "export", "sizeof", "typedef", "const", "struct", "for", "union", "volatile", "static", "mutable", "if", "do", "return", "goto", "enum", "else", "break", "extern", "asm", "case", "default", "register", "explicit", "typename", "switch", "continue", "inline", "readonly", "assign", "readwrite", "self", "@synchronized", "id", "typeof", "nonatomic", "IBOutlet", "IBAction", "strong", "weak", "copy", "in", "out", "inout", "bycopy", "byref", "oneway", "__strong", "__weak", "__block", "__autoreleasing", "@private", "@protected", "@public", "@try", "@property", "@end", "@throw", "@catch", "@finally", "@autoreleasepool", "@synthesize", "@dynamic", "@selector", "@optional", "@required", "@encode", "@package", "@import", "@defs", "@compatibility_alias", "__bridge", "__bridge_transfer", "__bridge_retained", "__bridge_retain", "__covariant", "__contravariant", "__kindof", "_Nonnull", "_Nullable", "_Null_unspecified", "__FUNCTION__", "__PRETTY_FUNCTION__", "__attribute__", "getter", "setter", "retain", "unsafe_unretained", "nonnull", "nullable", "null_unspecified", "null_resettable", "class", "instancetype", "NS_DESIGNATED_INITIALIZER", "NS_UNAVAILABLE", "NS_REQUIRES_SUPER", "NS_RETURNS_INNER_POINTER", "NS_INLINE", "NS_AVAILABLE", "NS_DEPRECATED", "NS_ENUM", "NS_OPTIONS", "NS_SWIFT_UNAVAILABLE", "NS_ASSUME_NONNULL_BEGIN", "NS_ASSUME_NONNULL_END", "NS_REFINED_FOR_SWIFT", "NS_SWIFT_NAME", "NS_SWIFT_NOTHROW", "NS_DURING", "NS_HANDLER", "NS_ENDHANDLER", "NS_VALUERETURN", "NS_VOIDRETURN")), new pz7("literal", Arrays.asList("false", "true", "FALSE", "TRUE", "nil", "YES", "NO", "NULL")), new pz7("built_in", Arrays.asList("dispatch_once_t", "dispatch_queue_t", "dispatch_sync", "dispatch_async", "dispatch_once")), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("int", "float", "char", "unsigned", "signed", "short", "long", "double", "wchar_t", "unichar", "void", "bool", "BOOL", "id|0", "_Bool")));
        i77 i77Var = new i77(null, null, null, null, null, "\\b(AV|CA|CF|CG|CI|CL|CM|CN|CT|MK|MP|MTK|MTL|NS|SCN|SK|UI|WK|XC)\\w+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "built_in", null, -33, 383);
        i77 i77Var2 = vy2.e;
        i77 i77Var3 = vy2.f;
        i77 i77Var4 = vy2.a;
        i77 i77Var5 = new i77(null, null, null, Collections.singletonList(new i77(null, "\\n", Collections.singletonList(i77Var4), null, null, "@\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -167, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -9, 383);
        Map singletonMap = Collections.singletonMap("keyword", "if else elif endif define undef warning error line pragma ifdef ifndef include");
        Double valueOf = Double.valueOf(0.0d);
        a = new z86("objectivec", a64.a, asList, false, null, false, null, Arrays.asList(i77Var, i77Var2, i77Var3, vy2.i, vy2.c, vy2.b, i77Var5, new i77(singletonMap, null, Arrays.asList(new i77(null, null, null, null, null, "\\\\\\n", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511), new i77(null, "\\n", Collections.singletonList(i77Var4), null, null, "\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", "string", -167, 127), new i77(null, "\\n", null, null, null, "<.*?>", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -163, 383), i77Var2, i77Var3), null, null, "#\\s*[a-z]+\\b", null, "$", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -166, 383), new i77(os6.I0(new pz7("$pattern", "[a-zA-Z@][a-zA-Z0-9_]*"), new pz7("keyword", Arrays.asList("@interface", "@class", "@protocol", "@implementation"))), null, Collections.singletonList(vy2.m), null, null, "(@interface|@class|@protocol|@implementation)\\b", null, "(\\{|$)", null, null, null, null, null, null, null, null, Boolean.TRUE, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "class", null, -131238, 383), new i77(null, null, null, null, null, "\\.[a-zA-Z_]\\w*", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511)), "</", I0, null, 25464);
    }
}
