package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class ys7 {
    public static final z86 a;

    static {
        pz7 pz7Var = new pz7("~contains~5", new i77(null, null, null, null, null, "\\$(f[asn]|t|vp[rtd]|children)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "keyword", null, -33, 383));
        pz7 pz7Var2 = new pz7("~contains~4", new i77(null, null, Collections.singletonList(vy2.a), null, null, "\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", -167, 255));
        Double valueOf = Double.valueOf(0.0d);
        a = new z86("openscad", os6.I0(pz7Var, pz7Var2, new pz7("~contains~2", new i77(null, null, null, null, null, "\\b\\d+(\\.\\d+)?(e-?\\d+)?", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -4129, 383))), Collections.singletonList("scad"), false, null, false, null, Arrays.asList(vy2.e, vy2.f, new j77("~contains~2"), new i77(Collections.singletonMap("keyword", "include use"), null, null, null, null, "include|use <", null, ">", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -162, 383), new j77("~contains~4"), new j77("~contains~5"), new i77(null, null, null, null, null, "[*!#%]", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511), new i77(null, null, Arrays.asList(new i77(null, null, Arrays.asList(new k77(), new j77("~contains~2"), new j77("~contains~4"), new j77("~contains~5"), new i77(null, null, null, null, null, "false|true|PI|undef", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "literal", null, -33, 383)), null, null, "\\(", null, "\\)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -165, 383), vy2.m), null, null, null, "module function", "=|\\{", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "function", null, -197, 383)), null, os6.I0(new pz7("keyword", "function module include use for intersection_for if else \\%"), new pz7("literal", "false true PI undef"), new pz7("built_in", "circle square polygon text sphere cube cylinder polyhedron translate rotate scale resize mirror multmatrix color offset hull minkowski union difference intersection abs sign sin cos tan acos asin atan atan2 floor round ceil ln log pow sqrt exp rands min max concat lookup str chr search version version_num norm cross parent_module echo import import_dxf dxf_linear_extrude linear_extrude rotate_extrude surface projection render children dxf_cross dxf_dim let assign")), null, 27512);
    }
}
