package defpackage;

import com.ishumei.smantifraud.l11l111l11Il;
import com.ishumei.smantifraud.l11l11I1111l;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Map;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class yw0 {
    public static final z86 a;

    static {
        Map I0 = os6.I0(new pz7("~contains~2", new i77(null, null, null, null, null, "(#\\d+)+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -33, 383)), new pz7("~contains~1", new i77(null, null, Collections.singletonList(new i77(null, null, null, null, null, "''", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, "'", null, "'", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -165, 383)));
        Map I02 = os6.I0(new pz7("keyword", Arrays.asList("div", "mod", "in", "and", "or", "not", "xor", "asserterror", "begin", "case", "do", "downto", "else", "end", "exit", "for", l11l111l11Il.l11l111ll11l, "if", "of", "repeat", "then", "to", "until", "while", "with", "var")), new pz7("literal", "false true"));
        Double valueOf = Double.valueOf(0.0d);
        i77 i77Var = new i77(null, null, null, null, null, null, null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "[\\w]+(?=\\=)", null, null, null, null, null, null, null, null, null, null, "attribute", -536875009, 255);
        j77 j77Var = new j77("~contains~1");
        j77 j77Var2 = new j77("~contains~2");
        i77 i77Var2 = new i77(null, null, null, null, null, "\\b\\d+(\\.\\d+)?(DT|D|T)", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "number", null, -4129, 383);
        i77 i77Var3 = new i77(null, null, null, null, null, "\"", null, "\"", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "string", null, -161, 383);
        i77 i77Var4 = vy2.h;
        i77 i77Var5 = new i77(null, null, null, null, null, null, null, null, null, null, null, null, Double.valueOf(3.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Arrays.asList("OBJECT", "\\s+", "(?:Table|Form|Report|Dataport|Codeunit|XMLport|MenuSuite|Page|Query)", "\\s+", "\\d+", "\\s+(?=[^\\s])", ".*", "$"), null, null, null, null, null, null, null, null, null, null, os6.I0(new pz7("1", "keyword"), new pz7("3", l11l11I1111l.l111l1111l1Il), new pz7("5", "number"), new pz7("7", "title")), -536875009, 255);
        List asList = Arrays.asList("procedure", "\\s+", "[a-zA-Z_][\\w@]*", "\\s*");
        Map I03 = os6.I0(new pz7("1", "keyword"), new pz7("3", "title.function"));
        i77 i77Var6 = new i77(Arrays.asList("div", "mod", "in", "and", "or", "not", "xor", "asserterror", "begin", "case", "do", "downto", "else", "end", "exit", "for", l11l111l11Il.l11l111ll11l, "if", "of", "repeat", "then", "to", "until", "while", "with", "var"), null, Arrays.asList(new j77("~contains~1"), new j77("~contains~2"), i77Var4), null, null, "\\(", null, "\\)", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "params", null, -166, 383);
        Boolean bool = Boolean.TRUE;
        a = new z86("cal", I0, null, true, null, false, null, Arrays.asList(i77Var, j77Var, j77Var2, i77Var2, i77Var3, i77Var4, i77Var5, new i77(null, null, Arrays.asList(i77Var6, vy2.e, new i77(null, null, Arrays.asList(new i77(null, null, null, null, null, "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", null, "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", null, null, null, null, valueOf, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "doctag", -69793, 255), new i77(null, null, null, null, null, "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, "\\{", null, "\\}", null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", -4261, 255), new i77(null, null, Arrays.asList(new i77(null, null, null, null, null, "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", null, "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", null, null, null, null, valueOf, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "doctag", -69793, 255), new i77(null, null, null, null, null, "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, "\\(\\*", null, "\\*\\)", null, null, null, null, Double.valueOf(10.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", -4261, 255)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, asList, null, null, null, null, null, null, null, null, null, null, I03, -536870917, 255)), "\\/\\*", I02, null, 25460);
    }
}
