package defpackage;

import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class z35 {
    public static final z86 a;

    static {
        i77 i77Var = new i77(null, null, null, null, null, "^!!!( (5|1\\.1|Strict|Frameset|Basic|Mobile|RDFa|XML\\b.*))?$", null, null, null, null, null, null, Double.valueOf(10.0d), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -4129, 383);
        Double valueOf = Double.valueOf(0.0d);
        Boolean bool = Boolean.TRUE;
        i77 i77Var2 = new i77(null, null, Arrays.asList(new i77(null, null, null, null, null, "[ ]*(?=(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):)", null, "(TODO|FIXME|NOTE|BUG|OPTIMIZE|HACK|XXX):", null, null, null, null, valueOf, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "doctag", -69793, 255), new i77(null, null, null, null, null, "[ ]+((?:I|a|is|so|us|to|at|if|in|it|on|[A-Za-z]+['](d|ve|re|ll|t|s|n)|[A-Za-z]+[-][a-z]+|[A-Za-z][a-z]{2,})[.]?[:]?([.][ ]|[ ])){3}", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511)), null, null, "^\\s*(!=#|=#|-#|/).*$", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "comment", -4261, 255);
        i77 i77Var3 = new i77(null, null, null, null, null, "^\\s*(-|=|!=)(?!#)", null, "$", null, null, null, null, null, null, Collections.singletonList("ruby"), bool, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -229537, 511);
        i77 i77Var4 = new i77(null, null, null, null, null, "\\w+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "selector-tag", null, -33, 383);
        i77 i77Var5 = new i77(null, null, null, null, null, "#[\\w-]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "selector-id", null, -33, 383);
        i77 i77Var6 = new i77(null, null, null, null, null, "\\.[\\w-]+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "selector-class", null, -33, 383);
        i77 i77Var7 = new i77(null, null, null, null, null, ":\\w+", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "attr", null, -33, 383);
        i77 i77Var8 = vy2.b;
        i77 i77Var9 = vy2.c;
        a = new z86("haml", a64.a, null, true, null, false, null, Arrays.asList(i77Var, i77Var2, i77Var3, new i77(null, null, Arrays.asList(i77Var4, i77Var5, i77Var6, new i77(null, null, Collections.singletonList(new i77(null, null, Arrays.asList(i77Var7, i77Var8, i77Var9, new i77(null, null, null, null, null, "\\w+", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511)), null, null, ":\\w+\\s*=>", null, ",\\s+", null, null, null, bool, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -526501, 511)), null, null, "\\{\\s*", null, "\\s*\\}", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -165, 511), new i77(null, null, Collections.singletonList(new i77(null, null, Arrays.asList(new i77(null, null, null, null, null, "\\w+", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "attr", null, -4129, 383), i77Var8, i77Var9, new i77(null, null, null, null, null, "\\w+", null, null, null, null, null, null, valueOf, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -4129, 511)), null, null, "\\w+\\s*=", null, "\\s+", null, null, null, bool, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -526501, 511)), null, null, "\\(\\s*", null, "\\s*\\)", null, null, null, null, null, null, null, null, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -131237, 511)), null, null, "^\\s*%", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "tag", null, -37, 383), new i77(null, null, null, null, null, "^\\s*[=\\x7e]\\s*", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -33, 511), new i77(null, null, null, null, null, "#\\{", null, "\\}", null, null, null, null, null, null, Collections.singletonList("ruby"), bool, bool, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, -229537, 511)), null, null, null, 31604);
    }
}
