package defpackage;

import com.ishumei.smantifraud.l11l11I1111l;
import java.util.Arrays;
import java.util.Collections;

/* compiled from: r8-map-id-7ff9306186985100d1d7914faebd9df19f297a91b56703aad83d9837746fff98 */
/* loaded from: classes.dex */
public abstract class zl1 {
    public static final z86 a = new z86("capnproto", a64.a, Collections.singletonList("capnp"), false, null, false, null, Arrays.asList(vy2.c, vy2.h, vy2.g, new i77(null, "\\n", null, null, null, "@0x[\\w\\d]{16};", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "meta", null, -35, 383), new i77(null, null, null, null, null, "@\\d+\\b", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, "symbol", null, -33, 383), new i77(null, null, null, Arrays.asList(new i77(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Arrays.asList("(struct|enum|interface)", "\\s+", "[a-zA-Z]\\w*"), null, null, null, null, null, null, null, null, null, null, null, -536870913, 511), new i77(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, Arrays.asList("extends", "\\s*\\(", "[a-zA-Z]\\w*", "\\s*\\)"), null, null, null, null, null, null, null, null, null, null, null, -536870913, 511)), null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, os6.I0(new pz7("1", "keyword"), new pz7("3", "title.class")), -9, 255)), null, os6.I0(new pz7("keyword", Arrays.asList("struct", "enum", "interface", "union", "group", "import", "using", "const", "annotation", "extends", "in", "of", "on", "as", "with", "from", "fixed")), new pz7(l11l11I1111l.l111l1111l1Il, Arrays.asList("Void", "Bool", "Int8", "Int16", "Int32", "Int64", "UInt8", "UInt16", "UInt32", "UInt64", "Float32", "Float64", "Text", "Data", "AnyPointer", "AnyStruct", "Capability", "List")), new pz7("literal", Arrays.asList("true", "false"))), null, 27512);
}
